name: TimerCheck
version: '${project.version}'
main: com.vmoizan.timercheck.TimerCheck
api-version: 1.20
depend: [ ProtocolLib ]
commands:
  brush:
    description: Edit your brush
    usage: /<command>