name: BrushPlugin
version: '${project.version}'
main: com.vmoizan.brushplugin.BrushPlugin
api-version: 1.20
depend: [ ProtocolLib ]
commands:
  brush:
    description: Edit your brush
    usage: /<command>